# Generated by Django 5.1 on 2024-10-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_alter_follow_list_followers_and_more'),
        ('posts', '0002_commentlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='people',
            field=models.ManyToManyField(related_name='comment_likers', to='Profile.profile'),
        ),
    ]
