# Generated by Django 5.1 on 2024-10-01 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifs', '0002_commentnotification'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentnotification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_notif', to='posts.comment'),
        ),
    ]
