# Generated by Django 5.1 on 2024-09-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_profile_private_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow_list',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers_followers', to='Profile.profile'),
        ),
        migrations.AlterField(
            model_name='follow_list',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers_following', to='Profile.profile'),
        ),
    ]
