# Generated by Django 5.1 on 2024-09-24 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_pending_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow_list',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers_followers', to='Profile.profile'),
        ),
        migrations.AlterField(
            model_name='follow_list',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers_following', to='Profile.profile'),
        ),
        migrations.CreateModel(
            name='block_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_user', to='Profile.profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_user', to='Profile.profile')),
            ],
        ),
    ]
