# Generated by Django 5.1 on 2024-10-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='encrypted_body',
        ),
    ]
